### ISSUE TITLE
Reaction arguments?

### ISSUE THREAD

**Issue by mindplay-dk** [zheksoon/dipole#10]
I was wondering about this line here:

https://github.com/zheksoon/dipole/blob/34e64ae09d0c4516aa6e24472a8626c0dd2c9af0/src/dipole.js#L327

What is `arguments` for?

As far as I can tell, `arguments` will be empty, since `run()` does not accept any arguments.

There are no calls to `run()` on a `Reaction` in user code, right?

Or is there a use-case where `manager` might pass arguments to `run()`, which would get forwarded?

**Comment by zheksoon** [comment]
> There are no calls to run() on a Reaction in user code, right?

No, there is :)
For example, React bindings:

https://github.com/zheksoon/dipole-react/blob/8d2b1027bf03005d5e2516536b4fcac82852bd7c/index.ts#L23

Here manager function is `triggerUpdate` lambda, which makes React to run the function component and execute reaction's `run()` method (which is component itself) with props and (obsolete) context arguments.

**Comment by mindplay-dk** [comment]
Okay, thanks for clarifying 🙂
