### ISSUE TITLE
Custom implementation of Set (HashSet)

### ISSUE THREAD

**Issue by mindplay-dk** [zheksoon/dipole#4]
Hi,

Just wondering, why do you use a custom implementation of `HashSet`?

I noticed it says in your README, "ES3 compatibility - should work even in a very old browsers" - so maybe that's why?

Still, the standard `Set` is in all browsers since 6+ years, so I wonder.

Either way, what do you think about a "ponyfill" approach instead?

That is, make your `HashSet` constructor and methods compatible with standard `Set` methods, so that you can produce two different builds? e.g. two builds, one of them smaller (and probably faster) for modern browsers.

**Comment by zheksoon** [comment]
Hi, thanks for reaching me!

Right, the use of custom HashSet is a feature for old browser compatibility. The first implementation of dipole initially was made with ES6 `Set`, but at some moment I decided to go with custom implementation, as it was compact and performant enough for the library' needs (https://github.com/zheksoon/dipole/blob/b8427110ef3ac11091a6383c6ceeb55efb65cc5b/src/dipole.js#L80)

The custom HashSet implements specific operations that are not available as a single method in ES6 `Set`:
1) Check if item exists in set and add it if not (`add` method) - in ES6 `Set` it would be two separate operations `add()` and `has()`
2) Allows to destructively iterate through HashSet's items - for `Set` it would be `forEach()` and `clear()`
3) Capacity reservation heuristics (https://github.com/zheksoon/dipole/blob/master/src/dipole.js#L65) 

About performance, I think it's on par with native `Set`.

I think in future it will definitely make sense to move dipole to `Set` and do ES6 compatible build, will see.

**Comment by mindplay-dk** [comment]
I think 1 and 2 can be done as just functions, where you pass the set to them - doesn't matter if it's native Set or an internal polyfill then.

As for 3, that sounds like an implementation detail? So with native Set, we should just trust it'll do what's best, although technically this could vary between browsers/versions.

I might try to do a PR, if it makes sense.

I really like this library. I've been using S.js, which works quite well - but I like the ergonomics of your library, with the more explicit get/set methods; more verbose, but probably easier for a new user to read and understand. Nice work. ✌️
