### ISSUE TITLE
fromGetter?

### ISSUE THREAD

**Issue by mrjjwright** [zheksoon/dipole#9]
Will you explain a usage for this utility?  I was trying to grok it.  Thanks!

**Comment by zheksoon** [comment]
Sure! Its purpose is to undo effect of `makeObservable` for some specific field.

Say, you created an object or class and ran `makeObservable` on it:

```js
const obj = makeObservable({ a: observable(1) }
```
and for some reason you don't want to pass the whole object for field manipulation, but only this specific observable. So you just do:

```js
const a = fromGetter(() => obj.a)
```

and later can do anything with the observable using `.get()` / `.set()` methods

**Comment by mrjjwright** [comment]
oh duh, yes, yes, nice, yes I will need that, kind of like the Mobx `getAtom` method, thank you!
